-- Run this in the Supabase SQL Editor to create the table
create table if not exists players (
    id bigint generated by default as identity primary key,
    name text not null,
    club text,
    era text,
    league text,
    position text,
    age int,
    market_value numeric,
    tier text,
    play_style text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
